export var BASE_URL = "https://apphunt.herokuapp.com/"
export var APP_COMMENTS_URL = BASE_URL + "comments/"
export var APP_COLLECTIONS_URL = BASE_URL + "app-collections"
export var USER_COLLECTIONS_URL = BASE_URL + "user-collections"
export var USERS_URL = BASE_URL + "users"
